package:
  name: harfbuzz
  version: 0.9.39

source:
  url: https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-0.9.39.tar.bz2
  fn: harfbuzz-0.9.39.tar.bz2

build:
  number: 1

requirements:
  build:
    - cairo
    - glib     >=2.33
    - freetype
  run:
    - cairo
    - glib   >=2.33
    - freetype

# harfbuzz has a cyclic dependency with freetype, so make
# sure that this build was done in the presence of a freetype
# that has been linked to a previous build of harfbuzz.
test:
  commands:
    - nm ${PREFIX}/lib/libharfbuzz.so | grep hb_ft_face_create > /dev/null

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
  license: MIT
  license_file: COPYING
  summary: An OpenType text shaping engine
  description: |
    HarfBuzz is a text shaping library. New Harbuzz targets various font
    technologies while Old HarfBuzz targets only OpenType fonts.
  doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
  dev_url: https://github.com/behdad/harfbuzz
