# This file created by conda-build 2.0.1+64.g6582e11.dirty
# meta.yaml template originally from:
# /media/sf_conda/conda-forge/staged-recipes/recipes/qt5, last modified Tue Sep 13 14:22:45 2016
# ------------------------------------------------

package:
    name: qt
    version: 5.6.0
source:
    fn: qt-everywhere-opensource-src-5.6.0.tar.xz
    patches:
        - 0005-Remove-unused-include-sys-signalfd.h.patch
        - 0006-zlib_dependency-Add-EXTRA_INCLUDEPATH-for-system-zli.patch
        - 0007-qtbase-CentOS5-Do-not-use-strict_c++.patch
        - 0008-qtbase-Ubuntu-disable_overlay_scrollbars.patch
        - 0010-qtbase-XCB-Auto-detect-xcb-glx-also-with-xcb-qt.patch
        - avx.patch
        - avx1.patch
        - avx2.patch
        - v4l2.patch
    sha256: 76a95cf6c1503290f75a641aa25079cd0c5a8fcd7cff07ddebff80a955b07de7
    url: http://download.qt.io/official_releases/qt/5.6/5.6.0/single/qt-everywhere-opensource-src-5.6.0.tar.xz
build:
    detect_binary_files_with_prefix: 'true'
    features: ''
    number: '0'
requirements:
    build:
        - bison
        - flex
        - fontconfig 2.11.*
        - freetype  2.5*
        - gst-plugins-base
        - icu 54.*
        - jpeg 8*
        - libpng >=1.6.21,<1.7
        - libxcb
        - openssl 1.0*
        - python
        - xz
        - zlib 1.2*
        - dbus
        - gcc
    run:
        - fontconfig 2.11.*
        - freetype 2.5*
        - gst-plugins-base
        - jpeg 8*
        - icu 54.*
        - libpng >=1.6.21,<1.7
        - libxcb
        - openssl 1.0*
        - zlib 1.2*
        - dbus
        - libgcc
test:
    files:
        - test
    requires:
        - gcc
about:
    home: http://www.qt.io
    license: LGPLv3
    summary: GUI application development framework
extra:
    recipe-maintainers:
        - ccordoba12
        - ddale
        - jdreaver
        - msarahan
        - mingwandroid
