# This file created by conda-build 1.20.3+48.g09ddcfe
# meta.yaml template originally from:
# /home/ilan/anaconda/packages/libtiff, last modified Thu Jun  2 17:29:37 2016
# ------------------------------------------------

package:
    name: libtiff
    version: 4.0.6
source:
    fn: tiff-4.0.6.tar.gz
    md5: d1d2e940dea0b5ad435f21f03d96dd72
    patches:
        - def_snprintf.patch
    url: ftp://ftp.remotesensing.org/pub/libtiff/tiff-4.0.6.tar.gz
build:
    features: ''
    number: '2'
requirements:
    build:
        - zlib 1.2.*
        - jpeg 8d
        - xz 5.2.*
        - jbig 2.1
    run:
        - zlib 1.2.*
        - jpeg 8d
        - xz 5.2.*
        - jbig 2.1
about:
    description: 'This software provides support for the Tag Image File Format (TIFF),
        a

        widely used format for storing image data.

        '
    doc_url: http://www.libtiff.org/document.html
    home: http://www.libtiff.org/
    license: BSD-like (http://www.libtiff.org/misc.html)
    license_family: BSD
    summary: Support for Tag Image File Format (TIFF)
