package:
  name: sqlalchemy
  version: 1.0.13

source:
  fn: SQLAlchemy-1.0.13.tar.gz
  url: https://pypi.python.org/packages/1d/e2/3df2e0e8cd3cf7e6e2905f1a3d44f1ba51c4fceab0968cc0cb3dcefcb53a/SQLAlchemy-1.0.13.tar.gz
  md5: cef0c4aa0e2464a6f903a9cac9b280d8

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - sqlalchemy
    - sqlalchemy.cprocessors
    - sqlalchemy.cresultproxy
    - sqlalchemy.cutils

about:
  home: http://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  summary: Database Abstraction Library
  description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that
    gives application developers the full power and flexibility of SQL.
  doc_url: http://docs.sqlalchemy.org/en/rel_1_0/
  dev_url: https://bitbucket.org/zzzeek/sqlalchemy/
