package:
  name: jinja2
  version: 2.8

source:
  fn: Jinja2-2.8.tar.gz
  url: https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.8.tar.gz
  md5: edb51693fe22c53cee5403775c71a99e

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - markupsafe
  run:
    - python
    - setuptools
    - markupsafe

test:
  imports:
    - jinja2

about:
  home: http://jinja.pocoo.org
  license: BSD
  license_file: LICENSE
  summary: An easy to use stand-alone template engine written in pure python.
  description: |
    Jinja2 is a full featured template engine for Python. It has full unicode
    support, an optional integrated sandboxed execution environment, widely
    used and BSD licensed.
  doc_url: http://jinja.pocoo.org/docs/dev/
  dev_url: https://github.com/pallets/jinja
