# This file created by conda-build 1.20.3+48.g09ddcfe
# meta.yaml template originally from:
# /home/ilan/anaconda/packages/libpng, last modified Thu Jun  2 17:00:49 2016
# ------------------------------------------------

package:
    name: libpng
    version: 1.6.22
source:
    fn: libpng-1.6.22.tar.gz
    md5: 4a84ef93939d18d589e8314ac742423a
    url: http://prdownloads.sourceforge.net/libpng/libpng-1.6.22.tar.gz
build:
    features: ''
requirements:
    build:
        - cmake
        - zlib 1.2.*
    run:
        - zlib 1.2.*
about:
    description: 'libpng is the official PNG reference library. It supports almost
        all PNG

        features, is extensible, and has been extensively tested for over 20 years.

        '
    dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
    doc_url: http://www.libpng.org/pub/png/libpng.html
    home: http://www.libpng.org/pub/png/libpng.html
    license: libpng license (http://www.libpng.org/pub/png/src/libpng-LICENSE.txt)
    license_family: Other
    license_file: LICENSE
    summary: The official PNG reference library
