# This file created by conda-build 1.20.3+48.g09ddcfe
# meta.yaml template originally from:
# /home/ilan/anaconda/packages/pycparser, last modified Sat May 28 11:16:28 2016
# ------------------------------------------------

package:
    name: pycparser
    version: '2.14'
source:
    fn: pycparser-2.14.tar.gz
    md5: a2bc8d28c923b4fe2b2c3b4b51a4f935
    url: https://pypi.python.org/packages/source/p/pycparser/pycparser-2.14.tar.gz
build:
    number: '1'
requirements:
    build:
        - python
    run:
        - python
test:
    imports:
        - pycparser
about:
    description: 'pycparser is a parser for the C language, written in pure Python.
        It is a

        module designed to be easily integrated into applications that need to

        parse C source code.

        '
    dev_url: https://github.com/eliben/pycparser#what-is-pycparser
    home: https://github.com/eliben/pycparser
    license: BSD
    license_file: LICENSE
    summary: Complete C99 parser in pure Python
