package:
  name: mkl
  version: 11.3.3

build:
  number: 0

requirements:
  build:
    - cio-bt        [osx]

about:
  home: http://software.intel.com/en-us/articles/intel-mkl/
  license: proprietary - Intel
  license_family: Proprietary
  summary: Math library for Intel and compatible processors
  description: |
    Intel Math Kernel Library (Intel MKL) accelerates math processing routines
    that increase application performance and reduce development time.
  doc_url: https://software.intel.com/en-us/articles/intel-math-kernel-library-documentation
