# This file created by conda-build 1.20.3+40.g9aca3db.dirty
# meta.yaml template originally from:
# /home/ilan/anaconda/packages/scikit-learn, last modified Mon May 30 22:19:14 2016
# ------------------------------------------------

package:
    name: scikit-learn
    version: 0.17.1
source:
    git_rev: 0.17.1
    git_url: https://github.com/scikit-learn/scikit-learn.git
build:
    features: ''
    number: '2'
requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - scipy
        - mkl-devel 11.3.3
    run:
        - python
        - numpy x.x
        - scipy
        - mkl 11.3.3
test:
    imports:
        - sklearn
    requires:
        - cio-bt
about:
    home: http://scikit-learn.org/stable/
    license: 3-clause BSD
    license_family: BSD
    license_file: COPYING
    summary: A set of python modules for machine learning and data mining
