package:
  name: ipaddress
  version: 1.0.16

source:
  fn: ipaddress-1.0.16.tar.gz
  url: https://pypi.python.org/packages/source/i/ipaddress/ipaddress-1.0.16.tar.gz
  md5: 1e27b62aa20f5b6fc200b2bdbf0d0847

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - ipaddress

about:
  home: https://github.com/phihag/ipaddress
  license: PSF
  license_file: LICENSE
  summary: IPv4/IPv6 manipulation library
  description: |
    Python 3.3's ipadress for older Python versions
