package:
  name: docutils
  version: 0.12

source:
  fn: docutils-0.12.tar.gz
  url: https://pypi.python.org/packages/source/d/docutils/docutils-0.12.tar.gz
  md5: 4622263b62c5c771c03502afa3157768
  patches:
    - file_insertion.patch

build:
  number: 2

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - docutils
    - docutils.core

about:
  home: http://docutils.sourceforge.net
  license: Public-Domain, PSF, 2-clause BSD, GPLv3
  license_family: GPL3
  license_file: COPYING.txt
  summary: Utilities for general- and special-purpose documentation
  description: |
    Docutils is an open-source text processing system for processing plaintext
    documentation into useful formats, such as HTML, LaTeX, man-pages, open-
    document, or XML. It includes reStructuredText, the easy to read, easy to
    use, what-you-see-is-what-you-get plaintext markup language.
  doc_url: http://docutils.sourceforge.net/docs/index.html
  dev_url: http://repo.or.cz/w/docutils.git
