package:
  name: path.py
  version: 8.2.1

source:
  fn: path.py-8.2.1.tar.gz
  url: https://pypi.python.org/packages/source/p/path.py/path.py-8.2.1.tar.gz
  md5: 7334796c9ed6036cb89bcd30d8409f91
  patches:
    - setup.patch

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - path

about:
  home: http://github.com/jaraco/path.py
  license: MIT
  summary: Module wrapper for os.path
  description: |
    path.py implements a path objects as first-class entities, allowing common
    operations on files to be invoked on those path objects directly.
  doc_url: https://pythonhosted.org/path.py/
  dev_url: https://github.com/jaraco/path.py
